apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: service-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service-registry
    app.kubernetes.io/part-of: service-registry
  name: service-registry
  namespace: jduimovich
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: service-registry
status:
  loadBalancer: {}
